### ISSUE TITLE
Establish the stability of the `httpClient` param on a Camel HTTP4 endpoint

### ISSUE THREAD

**Issue by ajs6f** [fcrepo4-labs/fcrepo-api-x#115]
Making this issue because the [Camel documentation workflow](https://camel.apache.org/how-do-i-edit-the-website.html) appears to be a bit involved and I expect it to take several days at least to work through it in order to determine whether `httpClient` is a reliable and supported function or not.

I _will_ find an answer to that question and bring it back to API-X.

**Comment by ajs6f** [comment]
Can't assign myself, @birkland -- please assign me.

**Comment by birkland** [comment]
[This](https://github.com/apache/camel/blob/master/components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpEndpoint.java#L68) annotation in `HttpEndpoint` is what suggests injectability of `HttpClient` as a param.  Other than that annotation, I haven't found any mention that this mechanism was or was not stable/supported

**Comment by whikloj** [comment]
Good 👀  @birkland, I saw that when working a local project, but assumed that a) a lack of documentation and b) the use of the term "producer" meant it was not for consumer endpoints.

**Comment by ajs6f** [comment]
1. How did you make the googly eyes!? I need to use that all the time!
2. My hope is that this is a documentation oversight in Camel and that the response will be "Oh, yeah, you can use that, we just forgot to note it in the [docs](https://camel.apache.org/http4.html)."
3. Even if they tell us otherwise, it might be not unreasonable for us to use this "feature" just until we can offload the pattern onto `camel-toolkit`, for which work I have created [this issue](https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/issues/138).

**Comment by whikloj** [comment]
1. `:eyes:` -> :eyes:, `:roll_eyes:` -> 🙄  
2. Documentation has always been camel's weak spot
3. If they tell us otherwise, could we use the `HttpClientConfigurer` to allow individuals to provide their own set of configuration for the http client? I don't fully understand this class or how it works, but it seems somewhat in line with what we want.

**Comment by ajs6f** [comment]
Tracking at https://issues.apache.org/jira/browse/CAMEL-11270

**Comment by birkland** [comment]
Fantastic, thanks so much @ajs6f !  Let's hope they bite

@whikloj I'm not sure how the `HttpClientConfigurer` is bound to the lifecycle of a given route.  If `HttpClientConfigurer` is invoked only once upon initial route building, then it probably can't be used.  If it's invoked per message, then it probably can.  I suspect it's the former, though.

**Comment by whikloj** [comment]
@birkland I'd agree that it is probably per route

**Comment by ajs6f** [comment]
Agreed. We _might_ be able to use it by altering the parameter in its method-- that is, swapping out the client they offer us to configure for a completely different client. But that is _ugly, fugly, mugly_.

**Comment by ajs6f** [comment]
We are golden. See the Camel issue linked above:


> Claus Ibsen added a comment - 5 hours ago
> 
> Its documented in the ascii docs which is the new docs
> https://github.com/apache/camel/blob/master/components/camel-http4/src/main/docs/http4-component.adoc
> 
> https://github.com/apache/camel/tree/master/components#components
>

We can safely use the `httpClient` parameter.
