### ISSUE TITLE
Investigate possible Fedora memory leak

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#21]
Investigate possible Fedora memory leak and seemingly related latency anomalies that complicate isolating latency effects due to API-X
- Continuously performing a GET on a Fedora resource results in increasingly poor 95th, 99th percentile latency figures; 200+ms 95th percentile latencies,  20ms 50th percentile observed after approximately 30 minutes of a single thread performing GET as fast as possible 
- Very slow memory leak, monotonically increasing number of ConcurrentHashMaps from somewhere in Modeshape
- Engage performance/scalability community?

**Comment by scossu** [comment]
Addressed in https://jira.duraspace.org/browse/FCREPO-2025

**Comment by birkland** [comment]
Fix merged into fcrepo4 master:
https://github.com/fcrepo4/fcrepo4/commit/1fb2e86b3b9bb55dc4ba7609cf8b853b0809e16e
