### ISSUE TITLE
Agree on an one or more extensions with common interest to develop concurrently with framework

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#22]
Create corresponding github issues.
- Sync & async validation?
  - Based on [SHACL draft](https://www.w3.org/TR/shacl/)?
    [Current reference implementation](https://github.com/TopQuadrant/shacl) is AGPL licensed, uses Jena snapshot version
- Async storage?
- Pick highly voted [use cases](https://wiki.duraspace.org/x/f5ApB)?

**Comment by scossu** [comment]
I would go with option 3: establish a time frame for another round of votes (likes), pick 1-3 top use cases depending on implementation efforts required, and update the descriptions of these use cases to reflect the latest architecture design (some of the workflows rely on assumptions that are no longer valid).

**Comment by birkland** [comment]
this was actually done in the form of Amherst's [repository extension services](https://gitlab.amherst.edu/acdc/repository-extension-services).  Additional extensions of common interest should be addressed in separate tickets, where applicable.
