### ISSUE TITLE
Describe the scope for service discovery & binding

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#3]
- Does SD&B need to describe the semantics of requests or responses of services or extensions?  Does SD&B need to describe how a service is invoked?  Does SD&B need to accommodate ‘selector’ that can be used to match objects bound to a given extension?
- See [discussion on SD&B proposal page](https://wiki.duraspace.org/x/bAhTB) 
- See minutes of [1/22](https://wiki.duraspace.org/x/YglTB) and [2/5](https://wiki.duraspace.org/x/mohcB) API-X meetings

**Comment by ajs6f** [comment]
IF SD&B _doesn't_ describe invocation, it seems a bit short-sighted. So I can discover a cool possible way to use a resource, and even the particular address of an implementation (for some value of that phrase), but then… what? Go out-of-band in some unspecifiable way?

**Comment by birkland** [comment]
Right, this task should also clarify the actors and intent in the scenarios SD&B supporting.

**Comment by acoburn** [comment]
IMO, SD&B _must_ describe invocation. Defining _how_ it will describe invocation is what needs to be clarified, though I assume RDF would be used.

**Comment by birkland** [comment]
After reflecting on this for a while, it seems to me that SD&B minimally needs to convey the notion of service type in its registry (e.g. a `sswap:Resource` or `msm:Service`, and link to an appropriate description.  The invocation model may very well be implicit.  For SSWAP services, invocation is uniform and defined by the protocol.  SSWAP service descriptions describe the semantics of the input and output graphs.  For the Minimal Service Model, the expectation is that the service description contains something like [SAWSDL](https://www.w3.org/TR/sawsdl/) or [hRESTS](http://www.wsmo.org/ns/hrests/).  

For supporting services that are largely opaque to API-X (where API-X may blindly proxy a request to an endpoint without reasoning about its contents), it's probably sufficient just to give these patterns names in an ontology (e.g. something like`apix:Proxy` or `apix:Filter`)

**Comment by birkland** [comment]
Just to update:

The current design proposal narrows the scope of SD&B a little as follows:
- SD&B contains description of services; which may describe details such as invocation methods, parameters, data types, etc.  API-X itsellf is agnostic about the ontologies used in these descriptions.  The term 'binding' as it applies to SD&B concerns binding/registering "instances of services\* to API-X
-  [Extension binding](https://docs.google.com/document/d/1PMM7Q6WVF6QrsyQ2YKoJItfj4w8DDPPx8rpFJVxEXco/edit#heading=h.45k9u3k4ip9p) is concerned describing how services are bound to objects, and how they are exposed
- [Execution](https://docs.google.com/document/d/1paxTnJb7jcELA1QfvNQrSaJiPnZ98derCAndkroz0b4/edit) is responsible for invoking services bound to objects.  There will be multiple implementations based on the kinds of services a given execution engine can invoke. API-X will match an execution engine impl to a particular bound service based on the extension definition and service definitions.

**Comment by birkland** [comment]
This is codified in 
- [service discovery and binding](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/service-discovery-and-binding.md)
- [execution and routing](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/execution-and-routing.md)
- [extension definition and binding](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/src/site/markdown/extension-definition-and-binding.md)
