### ISSUE TITLE
Describe the service invocation model provided by API-X core

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#4]
Compare & contrast the different approaches discussed so far, write up a proposal for an invocation model to be used API-X.  This could simply involve choosing an approach from below, a hybrid, or something else entirely.  Seek out consensus on the chosen appproach
- [SSWAP service invocation](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-10-309#Sec10) involves sending and receiving RDF graphs to services
- The [patterns doc](https://docs.google.com/document/d/1J8e5PQVDtN1PleIa76UgHWJiXGkYZDHz533yAUCa_lA/edit) suggests transparent http messaging
- [Camel-centric architecture](https://drive.google.com/file/d/0B0PHJTgoU3bkcV9aUGF5YXlSNDQ/view) suggests that extensions can provide camel routes that use camel DSLs to define how they integrate with services

**Comment by ajs6f** [comment]
Just a point of detail: SSWAP actually wants to send _OWL_ graphs around, which is slightly weird, but they are interested in and committed to inference from the beginning.

**Comment by birkland** [comment]
I've been doing some reading on SSWAP and similar technologies.  There seems to be a fair bit of work out there based on the [Minimal service model](http://kmi.github.io/iserve/latest/data-model.html#Minimal_Service_Model) in combination with various ontologies that provide semantic annotation to web services.  The end result is frameworks like [OmniVoke](http://omnivoke.kmi.open.ac.uk/), which use semantic annotations in order to automate the invocation of REST or WS- based APIs.  This appears to be the dominant pattern in the literature.  That being said SSWAP seems far less complex.

In my mind, it would be ideal if the architecture of API-X were adaptable to either pattern.  If we were to adopt an opinionated approach where development focused on one style, at the moment SSWAP appears to me to offer the highest cost/benefit ratio.

**Comment by birkland** [comment]
Just to update on where we are:

This is described by [API-X Design: Execution](https://docs.google.com/document/d/1paxTnJb7jcELA1QfvNQrSaJiPnZ98derCAndkroz0b4/edit)
