### ISSUE TITLE
Trusty URI?

### ISSUE THREAD

**Issue by ajs6f** [fcrepo4-labs/fcrepo-api-x#41]
An interesting and uncomplicated example for API-X might be offering [Trusty URIs](https://github.com/trustyuri/trustyuri-spec) over a repo.

http://trustyuri.net/

**Comment by DiegoPino** [comment]
@ajs6f Trusty URIs seem do be a good simple solution to some non trivial problem in RDF publishing. I wonder if you have some thoughts on the normalization proposed for RDF named Graphs and implementation concerns/ideas.

Probably what interests me most in this context is normalization:
- [I see here](https://github.com/trustyuri/trustyuri-spec#module-ra) a proposed graph normalization procedure, can't state its an algorithm, but seems easy to follow and to implement as such, but could be processor intensive.
- Until now, i was only aware of this RDF Normalization algorithm: https://json-ld.github.io/normalization/spec/ 

I wonder if the required normalization steps , or parts of it, like the lexicographical ordering could be  could be made part of Fedora4 in the future? Or it's better to keep this out of fedora 4 API specs? 

Looks like individual Fedora resource access is module `RB` aligned, and some of the @acoburn services exposing the whole subtree would be `RB`. `FA` looks to be almost a direct implementation of `sha` over an binary resource, so at first sight seems to be simpler.

Thanks for this. Very nice.

**Comment by ajs6f** [comment]
I would be _extremely_ disinclined to bake any such normalization into the CRUD spec. It might, theoretically, have some interest in the fixity spec. But even that is not too clear to me yet.

Yeah, I think `FA` is the low-hanging fruit here. The RDF stuff, in some ways, is more interesting, but more fraught as well.

**Comment by DiegoPino** [comment]
@ajs6f thanks. Got that same explanation 3 minutes ago from @acoburn and you both are right for N+1 reasons. Thanks 😄

**Comment by ajs6f** [comment]
These days, I'm happy to find out that I'm right about anything for any number of reasons.

**Comment by birkland** [comment]
Maybe there are use cases surrounding trusty URIs for explicit versions of resources? A resolution service as an extension?

**Comment by ajs6f** [comment]
@birkland In what context would that be more advisable than using the actual Fedora (Memento) version API?

**Comment by birkland** [comment]
@ajs6f I'm not fully sure I fully understand the use cases for trusty URIs, but it generally seems like one would be motivated to use them for situations where (a) they point to something stable (i.e. where the hash in the URI matches the hash of the content.   This is what made versions stick out to me) and (b) There is compelling value in minting/publishing a trusty URI for the resource.  

I'm less sure what the motivations for (b) may be, but in any case doubt it would be advisable to use trusty URIs as an alternative to memento in the general case.  Maybe it's kind of DOI like (or URI-shortener like) in the sense that publishing a trusty URI to the world comes from some specific case-by-case desire to do so for certain resources?  I'm really not sure.

**Comment by ajs6f** [comment]
I think the idea is that if you are handed a Trusty URI, and you dereference it to get some representation, you can use the checksum to see to it that neither:
- the long chain of network technology between you and the originating server
- or some bitrot or more sinister process at that server

have altered it. So... fixityish more than version stability.

**Comment by birkland** [comment]
@ajs6f Ah, I think I was imagining this from the perspective of someone who would want to publish trustyURIs for resources that won't (by policy) or can't (versions, by definition) change, as these URIs seem to be kind of a content-addressable way of approaching resolution of repository resources.  

Otherwise, I would think an implementation of trusty URIs would have to return a 404 if a resource no longer matches a the hash in trusty URI*, or if the identity of a resource that formerly had the hash is unknowable. 

So I agree that the use cases surrounding trusty URIs are fixity-ish, but also add that versioning is a built-in mechanism can be used to assure that a given trusty URI is durably resolvable.   

[*] To determine this, a trusty URI implementation would either have to know prior hash values for repository resources, or the identity of a resource would need to be present in the URI distinct from the hash.  In API-X, resource-scoped exposed services would meet the latter criteria.

**Comment by ajs6f** [comment]
I think we want to remember that a Trusty URI is an URI. It's not a construction with a query param or the like. IOW, if there is no resource at that URI, then 404 is appropriate, period. It's just like every other URI in that respect. So it's not about content-addressability. You don't start with a "base" URI and add a hash. You start with the whole Trusty URI, because if you don't have the hash, and you haven't yet resolved the URI, there is no way to generate the hash.

**Comment by ajs6f** [comment]
The crucial comment from Kuhn seems to me to be "trusty URIs are URIs that contain a certain kind of hash value that can be used to verify the respective resource". "_Verify_" is the important word, to me. Although I think he might have meant to use the word "representation" and not "resource".

**Comment by birkland** [comment]
@ajs6f Sorry, I may not be phrasing my comments in a clear manner (I've been in a series of all-day meetings).  The one and only point I'm trying to make is that someone publishing a trusty URI is likely to have motivation to assure that the URI remains resolvable [to a resource of fixed, matching state].  Providing trusty URIs to versions is a way to do that in Fedora.

**Comment by ajs6f** [comment]
Oh, yeah, sure. if you are interested enough to manage fixity publicly, you're probably interested in sane change management.

**Comment by birkland** [comment]
Great.  I think I was starting out with the assumption that trusty URIs would be primarily attractive to those who want to do exactly that - publish a URI publicly to a durable asset while also providing a simple mechanism of fixity verification.  (hence my leap to versioning as a mechanism of providing durability of a specific resource state).  If the desire to do so is strong enough, then the cost of going through effort to run API-X deploy a trustyURI extension would probably be worth it.  For one's own internal infrastructure and automated fixity checking processes, I think I was assuming that Fedora's existing fixity APIs would probably be good enough.

**Comment by ajs6f** [comment]
Right, I think this is about supplying a sense of fixity to people far away from the repo. Far from internal clients, we're talking about people who've never heard of "Fedora".

**Comment by ajs6f** [comment]
https://ws-dl.blogspot.com/2017/01/2017-01-15-summary-of-trusty-uris.html

**Comment by birkland** [comment]
@ajs6f Cool.  Oddly enough, I was just revisiting this last week to see if it made sense to propose as an extension-to-show-off for milestone 2.   Shall we assemble use cases?

Right now, I see:
1. Given a binary repository resource (LDP-NR), a trustyURI extension links to a trustyURI that resolves to that resource
2. A client can use the trustyURI generated by the API-X extension to download and validate the resource content

Is there anything else, or any refinement to the above?  For example is there a (2a) that involves the client verifying the downloaded content later, based on the hash being present in the file name?  Would the extension need to mind the file name via `Content-Disposition: attachment; filename=`?

**Comment by ajs6f** [comment]
It could be a cool extension, although I'm not sure how many people will have heard of trusty URIs, so some explanation might be necessary. I don't think the filename matters, but it might be interesting to show what can go _wrong_. In other words, to intentionally change the bitstream in the repo and then show how the trusty URI no longer resolves!

**Comment by birkland** [comment]
In that case, a demo data sounds like an ideal venue

**Comment by ajs6f** [comment]
Yeah, it could have some drama-- more than most things that have to do with fixity.
