### ISSUE TITLE
Fix Travis failures

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#45]
As noted in #42, builds are consistently successful when run locally on developer machines, but fail for various (not necessarily consistent) causes when executed on Travis

**Comment by acoburn** [comment]
@birkland I was noticing inconsistent travis failures for the Amherst repository services and I found that by turning off some of the unused system services on Travis, the builds were much more successful. Here's the travis configuration that I'm using: https://gitlab.amherst.edu/acdc/repository-extension-services/blob/master/.travis.yml

(I use gradle, but you should be able to map this to maven really easily).

**Comment by birkland** [comment]
Also, interesting note:  Jenkins built the latest PR and deployed snaps to Sonatype just fine (though it had non-fatal errors starting Karaf's internal SSH server):
http://jenkins.fcrepo.org/job/fcrepo-api-x/

**Comment by acoburn** [comment]
The errors related to starting the SSH server will occur whenever starting multiple instances of karaf (you get port conflicts unless you are very careful). I've seen those error a lot with my own code, and I have always ignored them, as they appear to be an artifact of testing with pax-exam.
