### ISSUE TITLE
Write stakeholder/evaluator guide

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#52]
This is a document that describes the features, installed extensions, and evaluation steps:

Guide for stakeholders, providing instructions for evaluation tasks, see [milestone doc](https://docs.google.com/document/d/10Zv_IpCwItMEuomB6Xpoy5d3x2914c6KzP9s5IcLzHk/edit#)
- Start/run demo
- Verify that all demo services are running
- Look at a pre-installed  Fedora object
- Look at a service document for a pre-installed fedora object
- Interact with an exposed service in browser
- Install an Amherst service
- Deploy an extension to expose the amherst service
- Ingest an object and verify the new service works on it
- Compare service documents from objects that bind to different services
- Look/execute some sparql queries
  - Find all objects that expose a particular service
  - Find all endpoints (exposed by api-x) on objects that implement a particular service
  - List all resource-scoped service endpoints for a particular object, and identify services they implement
- Look at code snippets that try to invoke a specific service on an object
  - when given the URI for a repository object, discover the URI for the service endpoint of the service and invoke it

**Comment by birkland** [comment]
@fcrepo4-labs/fcrepo-api-x-dev 
I took @emetsger google doc and split the content into three places:
* [The Duraspace wiki](https://wiki.duraspace.org/x/QpioB); this page focuses on eliciting participation in the specific task of evaluating the milestone, and provides advice on how to provide feedback, and what to keep in mind
* [The main README on GitHub](https://github.com/fcrepo4-labs/fcrepo-api-x-demo#summary) describes the how to get set up for running the demo with docker
* [The evaluation tasks on GitHub](https://github.com/fcrepo4-labs/fcrepo-api-x-demo/tree/master/exercises) The actual evaluation exercises, step-by-step.

That seems work well as a final form of the evaluator guide.  Can people comment on how it looks and falls together?  Thanks!

**Comment by emetsger** [comment]
I'll just comment here and say that I think the various documents read well.  The hyperlinks between the documents help them seem contiguous even though they serve different purposes.
