### ISSUE TITLE
Release api-x framework to Maven Central for demo

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#53]
This should be one of the last steps of creating the milestone, as bugs may be discovered and fixed in the process of assembling/testing the demo

Release as 0.1.0?

**Comment by birkland** [comment]
So here's a specific proposal:
 - Release the current API-X code base as 0.1.0 to Maven Central
 - bump `master` to 0.2.0-SNAPSHOT
 - Create maintenance branch for 0.1.1-SNAPSHOT; 
    - Any bugfixes discovered during the active phase of the demo will be additionally placed into this branch, and corresponding 0.1.1-SNAPSHOT-based docker images will be pushed out to dockerhub so that participants can pull in the fixes and continue evaluating
  - When we consider the evaluation done, we'll publish 0.1.1 to Maven, and stop maintaining a 0.1.x maintenance branch

The next milestone release of API-X will be 0.2.0, with a corresponding 0.2.1-SNAPSHOT pushed out to evaluators.  Keep up this pattern until API-X reaches 1.0.0.

**Comment by acoburn** [comment]
+1 on using 0.1.0 as an initial release
+1 on bumping master to 0.2.0-SNAPSHOT
+0 on the maintenance branch -- if it were me, I'd push those changes directly into master and, so long as there are no significant breaking changes, cut a 0.1.1 release directly from master. The maven release tooling will allow you to then set the dev version back to 0.2.0-SNAPSHOT.

Personally, I like keeping master 1 minor revision ahead of the current release -- it suggests to users that the snapshot is not necessarily compatible with the currently released artifacts. If it _is_ a mere patch update, that's easy to handle, but it doesn't give that expectation to anyone making use of the snapshot. That said, IMO as long as your release version is < 1.0.0, I don't expect projects to maintain strict semantic versioning.

**Comment by birkland** [comment]
OK - using master for cutting  0.1.1 is fine with me, that will probably be easier!

**Comment by acoburn** [comment]
easier++

**Comment by birkland** [comment]
This is in Maven Central as of last week:
http://central.maven.org/maven2/org/fcrepo/apix/
