### ISSUE TITLE
Allow for bypassing initialization when registry implementations/back-ends are not available.

### ISSUE THREAD

**Issue by emetsger** [fcrepo4-labs/fcrepo-api-x#62]
When the API-X features start up, they want to initialize state in the Fedora repository. 

When building docker images it would be useful to be able to install the API-X features at image build time.  

The problem is that a Fedora repository isn't available at Docker image build time, so installing the features fails.

It would be useful to be able to suppress the initialization of the Fedora repository in this case, allowing the features to be installed in a Docker image, bypassing the initialization of the Fedora repository.

**Comment by birkland** [comment]
Addressed in 7b2cae01a8a5e2fd7c1afa7dce32fef31f1a55c7
