### ISSUE TITLE
Peg docker images to specific versions in docker-compose.yaml

### ISSUE THREAD

**Issue by emetsger** [fcrepo4-labs/fcrepo-api-x#73]
For the milestone release, the docker-compose.yaml should refer to concrete versions of an image, not `:latest`.

Some consideration should be made regarding the docker image tags used for this milestone, depending on how long we think the milestone should continue to be viable.

**Comment by birkland** [comment]
We decided to use -latest for tracking the latest snapshot, but also published a tag which is bound to specific released versions.
