### ISSUE TITLE
fcrepo-camel-toolbox compatibility

### ISSUE THREAD

**Issue by birkland** [fcrepo4-labs/fcrepo-api-x#94]
As mentioned in #93, the [integration test](https://github.com/fcrepo4-labs/fcrepo-api-x/blob/master/fcrepo-api-x-integration/src/test/java/org/fcrepo/apix/integration/KarafServiceIndexingIT.java) for service document indexing is disabled.  fcrepo-camel-has [some updates](https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pull/115) that likely resolve the underlying incompatibilities.  

Try re-enabling `KarafServiceIndexingIT` with the latest fcrepo-camel-* snapshots.  If there are any issues, file tickets and fix them. Close this issue once fcrepo-camel-toolbox publishes its newest release, it has been incorporated as a dependency, and the integration test is fixed.

**Comment by acoburn** [comment]
I would also note that the current `fcrepo-camel-tests` project is, effectively, disabled because of these sorts of incompatibilities:

https://github.com/fcrepo4-exts/fcrepo-camel-tests/blob/master/pom.xml#L41-L42

But working from local branches, with https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pull/115 merged and the fcrepo-camel-tests updated to use the current snapshots, the Pax Exam tests all pass.

**Comment by birkland** [comment]
@acoburn OK, I can get all existing ITs (including the ignored one) to pass with the latest `fcrepo-camel-toolbox` snapshot.  That being said, [CAMEL-10405](https://issues.apache.org/jira/browse/CAMEL-10405) is still an issue - I get WARNINGs like [these](https://gist.github.com/birkland/c9a536943f8fdea09bb27ba5f1a92904) both in API-X and when building `fcrepo-camel-toolbox`.   What bothers me @davsclaus clearly states that ActiveMQ 5.14.1 does not support Camel 2.18.x in Karaf, yet all messaging-based ITs in `fcrepo-camel-toolbox` and `fcrepo-api-x` pass with that combination (albeit with the above warning message).  There were no pertinent details in [CAMEL-10405](https://issues.apache.org/jira/browse/CAMEL-10405)  or the corresponding [thread](http://camel.465427.n5.nabble.com/Karaf-4-0-7-Felix-JmsBinding-not-found-td5789099.html), so I don't think it's possible to assess the risk of using ActiveMQ 5.14.x + Camel 2.18.x outside of our ITs.

Also, I tried seeing if newer versions of dependencies fixed the issue without success:
* Camel 2.18.1 - same results
* ActiveMQ 5.14.2 (currently under vote for release) - same results
* ActiveMQ 5.15.0-SNAPSHOT - Did not work, OSGi was messed up.  Something in ActiveMQ was importing a package from guava `com.google.thirdparty.publicsuffix` that guava bundle was not exporting.

**Comment by acoburn** [comment]
@birkland yes, I still also get those errors, too. That said, the activemq component still seems to work. An alternative is to downgrade camel to 2.16.x, but there are things in 2.18 that I'd like to have.

I would add that I have been running these routes in karaf in our pre-production system for some time without issue (the WARNINGS you describe are present in the logs, but the routes themselves work correctly)

**Comment by davsclaus** [comment]
The ActiveMQ team fixed that guava thing today so try SNAPSHOT again (rebuild locally first)
https://github.com/apache/activemq/commit/e3d698b9d9c5cf97f5d462ee93f7027b97868da6
